/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Datos.Fraccion;
import Datos.ListaMatriz;
import Datos.Matriz;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Curso
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    
    private ArrayList<JComboBox<String>> combos=new ArrayList<>();
    private ArrayList<ListaMatriz> matricesIngresadas;
    private int filaseleccionadas = 0;
    private int columnaSeleccionadas=0;
    private ListaMatriz matrizSeleccionada = new ListaMatriz();
    public Principal() {
        initComponents();
        
        matricesIngresadas = new ArrayList<>();
        combos();
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxcolumna = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        boxfila = new javax.swing.JComboBox<>();
        btn_crear = new javax.swing.JButton();
        ventanaTab = new javax.swing.JTabbedPane();
        tab_pasos = new javax.swing.JPanel();
        MATRICES = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pasoscb = new javax.swing.JComboBox<>();
        btn_imprimir = new javax.swing.JButton();
        btn_secuencia = new javax.swing.JToggleButton();
        scroll = new javax.swing.JScrollPane();
        areatexto = new javax.swing.JTextArea();
        imprimirInversa = new javax.swing.JToggleButton();
        tab_op = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        sumacb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        suma_aplicar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_suma2 = new javax.swing.JTextField();
        txt_suma1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        suma2cb = new javax.swing.JComboBox<>();
        suma1cb = new javax.swing.JComboBox<>();
        resta_aplicar = new javax.swing.JButton();
        txt_resta2 = new javax.swing.JTextField();
        txt_resta1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        resta2cb = new javax.swing.JComboBox<>();
        resta1cb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        restacb = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cambio2cb = new javax.swing.JComboBox<>();
        cambio1cb = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cambio_aplicar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        escalarFcb = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        escalarF_aplicar = new javax.swing.JButton();
        escalarF = new javax.swing.JTextField();
        txt_suma1_1 = new javax.swing.JTextField();
        txt_suma2_2 = new javax.swing.JTextField();
        txt_resta1_1 = new javax.swing.JTextField();
        txt_resta2_2 = new javax.swing.JTextField();
        escalarF1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        op_suma = new javax.swing.JButton();
        op_resta = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        op_multiplicacion = new javax.swing.JButton();
        cb_opsuma1 = new javax.swing.JComboBox<>();
        cb_opsuma2 = new javax.swing.JComboBox<>();
        cb_opresta1 = new javax.swing.JComboBox<>();
        cb_opresta2 = new javax.swing.JComboBox<>();
        cb_opmulti1 = new javax.swing.JComboBox<>();
        cb_opmulti2 = new javax.swing.JComboBox<>();
        calc_inversa = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        cb_inversa = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        determinante = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        matrizNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        boxcolumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Columna", "2 Columnas", "3 Columnas", "4 Columnas", "5 Columnas" }));
        boxcolumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxcolumnaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione el tamaño de la matriz que desea ingresar a la lista de matrices del programa");

        boxfila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Fila", "2 Filas", "3 Filas", "4 Filas", "5 Filas" }));
        boxfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxfilaActionPerformed(evt);
            }
        });

        btn_crear.setText("Crear");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        MATRICES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MATRICESMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione la matriz para la cual desea realizar las operaciones realizadas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ImprimirPaso:");

        pasoscb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principal" }));

        btn_imprimir.setText("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        btn_secuencia.setText("ImprimirSecuencia");
        btn_secuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secuenciaActionPerformed(evt);
            }
        });

        areatexto.setColumns(20);
        areatexto.setRows(5);
        scroll.setViewportView(areatexto);

        imprimirInversa.setText("ImprimirInversa");
        imprimirInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirInversaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_pasosLayout = new javax.swing.GroupLayout(tab_pasos);
        tab_pasos.setLayout(tab_pasosLayout);
        tab_pasosLayout.setHorizontalGroup(
            tab_pasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_pasosLayout.createSequentialGroup()
                .addGroup(tab_pasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(tab_pasosLayout.createSequentialGroup()
                        .addComponent(MATRICES, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pasoscb, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_secuencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imprimirInversa)))
                .addGap(0, 38, Short.MAX_VALUE))
            .addComponent(scroll)
        );
        tab_pasosLayout.setVerticalGroup(
            tab_pasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_pasosLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(tab_pasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MATRICES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(pasoscb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_imprimir)
                    .addComponent(btn_secuencia)
                    .addComponent(imprimirInversa))
                .addGap(18, 18, 18)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ventanaTab.addTab("Pasos", tab_pasos);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Suma de Filas");

        sumacb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fn-->Fm", "xFn-->Fm", "Fn-->xFm", "xFn-->xFm" }));

        jLabel6.setText("-------------------------------------------------------------------------------------");

        suma_aplicar.setText("Aplicar");
        suma_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suma_aplicarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Las operaciones seran realizadas en la matriz seleccionada");

        txt_suma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_suma2ActionPerformed(evt);
            }
        });

        txt_suma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_suma1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("FilaN");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("FilaM");

        resta_aplicar.setText("Aplicar");
        resta_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resta_aplicarActionPerformed(evt);
            }
        });

        txt_resta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resta2ActionPerformed(evt);
            }
        });

        txt_resta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resta1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("FilaN");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("FilaM");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Resta de Filas");

        restacb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fn-->Fm", "xFn-->Fm", "Fn-->xFm", "xFn-->xFm" }));

        jLabel15.setText("-------------------------------------------------------------------------------------");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("FilaN");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("FilaM");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Cambio de Filas");

        jLabel19.setText("-------------------------------------------------------------------------------------");

        cambio_aplicar.setText("Aplicar");
        cambio_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambio_aplicarActionPerformed(evt);
            }
        });

        jLabel20.setText("<---->");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("FilaN");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Fila por Escalar ");

        jLabel24.setText("-------------------------------------------------------------------------------------");

        escalarF_aplicar.setText("Aplicar");
        escalarF_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalarF_aplicarActionPerformed(evt);
            }
        });

        escalarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalarFActionPerformed(evt);
            }
        });

        txt_suma1_1.setText("1");
        txt_suma1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_suma1_1ActionPerformed(evt);
            }
        });

        txt_suma2_2.setText("1");

        txt_resta1_1.setText("1");
        txt_resta1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resta1_1ActionPerformed(evt);
            }
        });

        txt_resta2_2.setText("1");
        txt_resta2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resta2_2ActionPerformed(evt);
            }
        });

        escalarF1.setText("1");
        escalarF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalarF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_opLayout = new javax.swing.GroupLayout(tab_op);
        tab_op.setLayout(tab_opLayout);
        tab_opLayout.setHorizontalGroup(
            tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_opLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 494, Short.MAX_VALUE))
            .addGroup(tab_opLayout.createSequentialGroup()
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(tab_opLayout.createSequentialGroup()
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tab_opLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(67, 67, 67))
                            .addGroup(tab_opLayout.createSequentialGroup()
                                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_resta2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tab_opLayout.createSequentialGroup()
                                        .addComponent(txt_resta1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resta1cb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_resta2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(resta2cb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(tab_opLayout.createSequentialGroup()
                            .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16)
                                .addComponent(cambio1cb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17)
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(cambio2cb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(102, 102, 102))
                        .addGroup(tab_opLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(156, 156, 156)
                            .addComponent(cambio_aplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_resta1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tab_opLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(restacb, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(resta_aplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(364, 486, Short.MAX_VALUE))
            .addGroup(tab_opLayout.createSequentialGroup()
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tab_opLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(sumacb, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suma_aplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(tab_opLayout.createSequentialGroup()
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tab_opLayout.createSequentialGroup()
                                .addComponent(txt_suma1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suma1cb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_suma2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tab_opLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel10))
                            .addGroup(tab_opLayout.createSequentialGroup()
                                .addComponent(txt_suma1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_suma2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(suma2cb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(tab_opLayout.createSequentialGroup()
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(escalarF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(escalarF1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(escalarF_aplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_opLayout.createSequentialGroup()
                                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(escalarFcb, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(188, 188, 188)))))
                .addGap(144, 144, 144))
        );
        tab_opLayout.setVerticalGroup(
            tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_opLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(20, 20, 20)
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_opLayout.createSequentialGroup()
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sumacb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suma_aplicar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(4, 4, 4)
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_suma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_suma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suma2cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suma1cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_suma1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_suma2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(tab_opLayout.createSequentialGroup()
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(escalarF_aplicar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addGap(4, 4, 4)
                        .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(escalarFcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(escalarF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(escalarF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)))
                .addGap(22, 22, 22)
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(restacb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resta_aplicar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(4, 4, 4)
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_resta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_resta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resta2cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resta1cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_resta1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_resta2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(cambio_aplicar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(4, 4, 4)
                .addGroup(tab_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambio2cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambio1cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        ventanaTab.addTab("Operaciones Elementales", tab_op);

        op_suma.setText("Operar");
        op_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_sumaActionPerformed(evt);
            }
        });

        op_resta.setText("Operar");
        op_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_restaActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Suma de Matrices");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Resta de Matrices");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Multiplicacion");

        op_multiplicacion.setText("Operar");
        op_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_multiplicacionActionPerformed(evt);
            }
        });

        cb_opresta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_opresta1ActionPerformed(evt);
            }
        });

        calc_inversa.setText("Calcular");
        calc_inversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_inversaActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Inversa");

        jButton1.setText("det");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        determinante.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(op_suma)
                            .addGap(38, 38, 38)
                            .addComponent(jLabel22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(op_resta)
                                .addComponent(op_multiplicacion))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel25)
                                .addComponent(jLabel27))))
                    .addComponent(calc_inversa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_opmulti1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_opsuma1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_opresta1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_inversa, 0, 82, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_opsuma2, 0, 80, Short.MAX_VALUE)
                    .addComponent(cb_opresta2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_opmulti2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(determinante, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_suma)
                    .addComponent(jLabel22)
                    .addComponent(cb_opsuma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_opsuma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(determinante))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_resta)
                    .addComponent(jLabel25)
                    .addComponent(cb_opresta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_opresta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_multiplicacion)
                    .addComponent(jLabel26)
                    .addComponent(cb_opmulti1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_opmulti2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calc_inversa)
                    .addComponent(jLabel27)
                    .addComponent(cb_inversa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        ventanaTab.addTab("Operaciones con matrices", jPanel1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Matriz Seleccionada :");

        matrizNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        matrizNombre.setText("No hay matriz slecionada!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxfila, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxcolumna, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(matrizNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ventanaTab))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxfila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(boxcolumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_crear)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matrizNombre)
                        .addContainerGap())
                    .addComponent(ventanaTab)))
        );

        ventanaTab.getAccessibleContext().setAccessibleName("Pasos");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxcolumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxcolumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxcolumnaActionPerformed

    private void boxfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxfilaActionPerformed
       
    }//GEN-LAST:event_boxfilaActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        String seleccion = boxfila.getSelectedIndex()+"+"+boxcolumna.getSelectedIndex();
        String nombre  =   JOptionPane.showInputDialog(null,"Ingrese el nombre de la matriz");
        ventanaMatriz VentanaMatriz = new ventanaMatriz(seleccion,this,nombre.toUpperCase());
        VentanaMatriz.setVisible(true);
        
    }//GEN-LAST:event_btn_crearActionPerformed

    private void escalarF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalarF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escalarF1ActionPerformed

    private void txt_resta2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resta2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resta2_2ActionPerformed

    private void txt_resta1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resta1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resta1_1ActionPerformed

    private void txt_suma1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_suma1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_suma1_1ActionPerformed

    private void escalarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalarFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escalarFActionPerformed

    private void escalarF_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalarF_aplicarActionPerformed
        Fraccion f = new Fraccion(Integer.parseInt(escalarF.getText()), Integer.parseInt(escalarF1.getText()));
        matrizSeleccionada.duplicar();
        matrizSeleccionada.getUltimo().escalarPorFila(f,escalarFcb.getSelectedIndex());
        matrizSeleccionada.agregarOperacion(f.getNominador()+"/"+f.getDenominador()+"Fn");

        // TODO add your handling code here:
    }//GEN-LAST:event_escalarF_aplicarActionPerformed

    private void cambio_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambio_aplicarActionPerformed
        matrizSeleccionada.duplicar();
        matrizSeleccionada.getUltimo().cambioFila(cambio1cb.getSelectedIndex(), cambio2cb.getSelectedIndex());
        matrizSeleccionada.agregarOperacion("Fn"+(cambio1cb.getSelectedIndex()+1)+"+"+"<-->"+"Fm"+(cambio2cb.getSelectedIndex()+1));
        JOptionPane.showMessageDialog(null, "Operacion realizada");
        actualizar();

        // TODO add your handling code here:
    }//GEN-LAST:event_cambio_aplicarActionPerformed

    private void txt_resta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resta1ActionPerformed

    private void txt_resta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_resta2ActionPerformed

    private void resta_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resta_aplicarActionPerformed
        try {
            switch(restacb.getSelectedItem().toString()){
                case "Fn-->Fm":
                matrizSeleccionada.duplicar();
                matrizSeleccionada.getUltimo().restaFila(resta1cb.getSelectedIndex(),resta2cb.getSelectedIndex() );
                matrizSeleccionada.agregarOperacion("Resta:"+"Fn-->Fm");
                break;
                case "xFn-->Fm":
                Fraccion f1 = new Fraccion(Integer.parseInt(txt_resta1.getText()),Integer.parseInt(txt_resta1_1.getText()));
                matrizSeleccionada.duplicar();
                matrizSeleccionada.getUltimo().restaFila(f1, resta1cb.getSelectedIndex(), "null",resta2cb.getSelectedIndex());
                matrizSeleccionada.agregarOperacion("Resta:"+f1.getNominador()+"/"+f1.getDenominador()+"xFn-->Fm");
                break;
                case "Fn-->xFm":
                Fraccion f2 = new Fraccion(Integer.parseInt(txt_resta2.getText()),Integer.parseInt(txt_resta2_2.getText()));
                matrizSeleccionada.duplicar();
                matrizSeleccionada.getUltimo().restaFila("null", resta1cb.getSelectedIndex(),f2,resta2cb.getSelectedIndex());
                matrizSeleccionada.agregarOperacion("Resta:"+"Fn-->"+f2.getNominador()+"/"+f2.getDenominador()+"Fm");
                break;
                case "xFn-->xFm":
                Fraccion f3 = new Fraccion(Integer.parseInt(txt_resta1.getText()),Integer.parseInt(txt_resta1_1.getText()));
                Fraccion f4 = new Fraccion(Integer.parseInt(txt_resta2.getText()),Integer.parseInt(txt_resta2_2.getText()));
                matrizSeleccionada.duplicar();
                matrizSeleccionada.getUltimo().restaFila(f3,resta1cb.getSelectedIndex(),f4, resta2cb.getSelectedIndex());
                matrizSeleccionada.agregarOperacion("Resta:"+f3.getNominador()+"/"+f3.getDenominador()+"xFn-->"+f4.getNominador()+"/"+f4.getDenominador()+"xFm");
                break;
            }
            JOptionPane.showMessageDialog(null, "Agregado");
            actualizar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor ingrese los valores correctos "+e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_resta_aplicarActionPerformed

    private void txt_suma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_suma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_suma1ActionPerformed

    private void txt_suma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_suma2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_suma2ActionPerformed

    private void suma_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suma_aplicarActionPerformed
        try {
            switch(sumacb.getSelectedItem().toString()){
                case "Fn-->Fm":
                System.out.println("empieza");
                matrizSeleccionada.duplicar();
                System.out.println("paso");
                matrizSeleccionada.getUltimo().sumaFila(suma1cb.getSelectedIndex(),suma2cb.getSelectedIndex() );
                System.out.println("paso1");
                matrizSeleccionada.agregarOperacion("Suma:"+"Fn-->Fm");
                System.out.println("paso2");
                break;
                case "xFn-->Fm":
                Fraccion f1 = new Fraccion(Integer.parseInt(txt_suma1.getText()),Integer.parseInt(txt_suma1_1.getText()));
                matrizSeleccionada.duplicar();
                matrizSeleccionada.getUltimo().sumaFila(f1, suma1cb.getSelectedIndex(), "null",suma2cb.getSelectedIndex());

                matrizSeleccionada.agregarOperacion("Suma:"+f1.getNominador()+"/"+f1.getDenominador()+"xFn-->Fm");

                break;
                case "Fn-->xFm":
                Fraccion f2 = new Fraccion(Integer.parseInt(txt_suma2.getText()),Integer.parseInt(txt_suma2_2.getText()));
                matrizSeleccionada.duplicar();
                matrizSeleccionada.getUltimo().sumaFila("null", suma1cb.getSelectedIndex(),f2,suma2cb.getSelectedIndex());
                matrizSeleccionada.agregarOperacion("Suma:"+"Fn-->"+f2.getNominador()+"/"+f2.getDenominador()+"Fm");
                break;
                case "xFn-->xFm":
                Fraccion f3 = new Fraccion(Integer.parseInt(txt_suma1.getText()),Integer.parseInt(txt_suma1_1.getText()));
                Fraccion f4 = new Fraccion(Integer.parseInt(txt_suma2.getText()),Integer.parseInt(txt_suma2_2.getText()));
                matrizSeleccionada.duplicar();
                matrizSeleccionada.getUltimo().sumaFila(f3,suma1cb.getSelectedIndex(),f4, suma2cb.getSelectedIndex());
                matrizSeleccionada.agregarOperacion("Suma:"+f3.getNominador()+"/"+f3.getDenominador()+"xFn-->"+f4.getNominador()+"/"+f4.getDenominador()+"xFm");
                break;
            }
            JOptionPane.showMessageDialog(null, "Operacion realizada");
            actualizar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor ingrese los valores correctos: "+e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_suma_aplicarActionPerformed
    public void OPS(){
            cb_opsuma1.removeAllItems();
            cb_opsuma2.removeAllItems();
            cb_opresta1.removeAllItems();
            cb_opresta2.removeAllItems();
            cb_opmulti1.removeAllItems();
            cb_opmulti2.removeAllItems();
            cb_inversa.removeAllItems();
        for (int i = 0; i < matricesIngresadas.size(); i++) {
            cb_inversa.addItem(matricesIngresadas.get(i).getNombre());
            cb_opsuma1.addItem(matricesIngresadas.get(i).getNombre());
            cb_opsuma2.addItem(matricesIngresadas.get(i).getNombre());
            cb_opresta1.addItem(matricesIngresadas.get(i).getNombre());
            cb_opresta2.addItem(matricesIngresadas.get(i).getNombre());
            cb_opmulti1.addItem(matricesIngresadas.get(i).getNombre());
            cb_opmulti2.addItem(matricesIngresadas.get(i).getNombre());
            
            
        }
        
    }
    private void btn_secuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secuenciaActionPerformed
        try {
            //System.out.println(pasoscb.getSelectedIndex());
            areatexto.setText("");
            areatexto.setText(matrizSeleccionada.imprimirTXT());

        } catch (Exception e) {
            System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_secuenciaActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        try {
            //System.out.println(pasoscb.getSelectedIndex());
            areatexto.setText("");
            areatexto.setText(matrizSeleccionada.getMatrices().get(pasoscb.getSelectedIndex()).imprimirMatriz());
            
        } catch (Exception e) {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void MATRICESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MATRICESMouseClicked

        actualizar();

        // TODO add your handling code here:
    }//GEN-LAST:event_MATRICESMouseClicked

    private void cb_opresta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_opresta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_opresta1ActionPerformed

    private void op_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_sumaActionPerformed

        ListaMatriz tmp = new ListaMatriz();
        Matriz m = new Matriz();
        m = m.sumaMatriz(obtenerMatrizPorNombre(cb_opsuma1.getSelectedItem().toString()),obtenerMatrizPorNombre(cb_opsuma2.getSelectedItem().toString()));
        tmp.agregarMatriz(m);
        String nombre  =   JOptionPane.showInputDialog(null,"Ingrese el nombre para la matriz de resultado");
        tmp.setNombre(nombre);
        matricesIngresadas.add(tmp);
        MATRICES.addItem(nombre.toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_op_sumaActionPerformed

    private void op_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_multiplicacionActionPerformed
       ListaMatriz tmp = new ListaMatriz();
        Matriz m = new Matriz();
        m = m.producto(obtenerMatrizPorNombre(cb_opsuma1.getSelectedItem().toString()),obtenerMatrizPorNombre(cb_opsuma2.getSelectedItem().toString()));
        tmp.agregarMatriz(m);
        String nombre  =   JOptionPane.showInputDialog(null,"Ingrese el nombre para la matriz de resultado");
        tmp.setNombre(nombre);
        matricesIngresadas.add(tmp);
        MATRICES.addItem(nombre.toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_op_multiplicacionActionPerformed

    private void op_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_restaActionPerformed
        ListaMatriz tmp = new ListaMatriz();
        Matriz m = new Matriz();
        m = m.restaMatriz(obtenerMatrizPorNombre(cb_opsuma1.getSelectedItem().toString()),obtenerMatrizPorNombre(cb_opsuma2.getSelectedItem().toString()));
        tmp.agregarMatriz(m);
        String nombre  =   JOptionPane.showInputDialog(null,"Ingrese el nombre para la matriz de resultado");
        tmp.setNombre(nombre);
        matricesIngresadas.add(tmp);
        MATRICES.addItem(nombre.toUpperCase());

// TODO add your handling code here:
    }//GEN-LAST:event_op_restaActionPerformed

    private void calc_inversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_inversaActionPerformed
        

        // TODO add your handling code here:
    }//GEN-LAST:event_calc_inversaActionPerformed

    private void imprimirInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirInversaActionPerformed
        try {
            //System.out.println(pasoscb.getSelectedIndex());
            areatexto.setText("");
            areatexto.setText(obtenerInversa(MATRICES.getSelectedItem().toString()).imprimirMatriz());
            matrizSeleccionada.imprimir();
        } catch (Exception e) {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_imprimirInversaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        determinante.setText(obtenerMatrizPorNombre(MATRICES.getSelectedItem().toString()).determinante()+"");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public void nada(){}    public boolean esCuadrada(){
        if (filaseleccionadas == columnaSeleccionadas){
            return true;
        }
        return false;
    }
    public Matriz obtenerMatrizPorNombre(String nombre){
        for (int i = 0; i < matricesIngresadas.size(); i++) {
            if(matricesIngresadas.get(i).getNombre()==nombre){
                return matricesIngresadas.get(i).getUltimo();
            }
            
        }
        return null;
    }
    public Matriz obtenerInversa(String nombre){
        for (int i = 0; i < matricesIngresadas.size(); i++) {
            if(matricesIngresadas.get(i).getNombre()==nombre){
                return matricesIngresadas.get(i).getInversa();
            }
            
        }
        return null;
    }
    public void actualizar(){
        try {
               
                matrizNombre.setText(MATRICES.getSelectedItem().toString());               
                DefaultComboBoxModel model = (DefaultComboBoxModel) pasoscb.getModel();
                model.removeAllElements();
                
                pasoscb.addItem("Principal");
            for (int i = 1; i < matrizSeleccionada.size(); i++) {           
                pasoscb.addItem(i+"");

            }
            for (int i = 0; i < matricesIngresadas.size(); i++) {
                if (matricesIngresadas.get(i).getNombre()== MATRICES.getSelectedItem().toString()){
                    matrizSeleccionada = matricesIngresadas.get(i);
                    filaseleccionadas =matricesIngresadas.get(i).getMatrices().get(0).filasSize();
                    columnaSeleccionadas = matricesIngresadas.get(i).getMatrices().get(0).columnasSize();
                }
                
            }
            setcombos();
            
            
        } catch (Exception e) {
        }
    }
    public void agregarCombo(String item){
        MATRICES.addItem(item);
    }
    public ArrayList<ListaMatriz> getMatricesIngresadas() {
        return matricesIngresadas;
    }

    public void setMatricesIngresadas(ArrayList<ListaMatriz> matricesIngresadas) {
        this.matricesIngresadas = matricesIngresadas;
    }
    public void agregarAMatricesIngresadas(ListaMatriz lm){
        matricesIngresadas.add(lm);
    }
    
    
    public void setcombos(){
        for (int i = 0; i < combos.size(); i++) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) combos.get(i).getModel();
            model.removeAllElements();
            
        }
        for (int i = 0; i < combos.size(); i++) {
            for (int j = 0; j < filaseleccionadas; j++) {
                combos.get(i).addItem(""+(j+1));
                
            }
            
            
        }
    }
    private void combos(){
        combos.add(suma1cb);
        combos.add(suma2cb);
        combos.add(resta1cb);
        combos.add(resta2cb);
        combos.add(cambio1cb);
        combos.add(cambio2cb);
        combos.add(escalarFcb);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MATRICES;
    private javax.swing.JTextArea areatexto;
    private javax.swing.JComboBox<String> boxcolumna;
    private javax.swing.JComboBox<String> boxfila;
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JToggleButton btn_secuencia;
    private javax.swing.JButton calc_inversa;
    private javax.swing.JComboBox<String> cambio1cb;
    private javax.swing.JComboBox<String> cambio2cb;
    private javax.swing.JButton cambio_aplicar;
    private javax.swing.JComboBox<String> cb_inversa;
    private javax.swing.JComboBox<String> cb_opmulti1;
    private javax.swing.JComboBox<String> cb_opmulti2;
    private javax.swing.JComboBox<String> cb_opresta1;
    private javax.swing.JComboBox<String> cb_opresta2;
    private javax.swing.JComboBox<String> cb_opsuma1;
    private javax.swing.JComboBox<String> cb_opsuma2;
    private javax.swing.JLabel determinante;
    private javax.swing.JTextField escalarF;
    private javax.swing.JTextField escalarF1;
    private javax.swing.JButton escalarF_aplicar;
    private javax.swing.JComboBox<String> escalarFcb;
    private javax.swing.JToggleButton imprimirInversa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel matrizNombre;
    private javax.swing.JButton op_multiplicacion;
    private javax.swing.JButton op_resta;
    private javax.swing.JButton op_suma;
    private javax.swing.JComboBox<String> pasoscb;
    private javax.swing.JComboBox<String> resta1cb;
    private javax.swing.JComboBox<String> resta2cb;
    private javax.swing.JButton resta_aplicar;
    private javax.swing.JComboBox<String> restacb;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JComboBox<String> suma1cb;
    private javax.swing.JComboBox<String> suma2cb;
    private javax.swing.JButton suma_aplicar;
    private javax.swing.JComboBox<String> sumacb;
    private javax.swing.JPanel tab_op;
    private javax.swing.JPanel tab_pasos;
    private javax.swing.JTextField txt_resta1;
    private javax.swing.JTextField txt_resta1_1;
    private javax.swing.JTextField txt_resta2;
    private javax.swing.JTextField txt_resta2_2;
    private javax.swing.JTextField txt_suma1;
    private javax.swing.JTextField txt_suma1_1;
    private javax.swing.JTextField txt_suma2;
    private javax.swing.JTextField txt_suma2_2;
    private javax.swing.JTabbedPane ventanaTab;
    // End of variables declaration//GEN-END:variables
}
