/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.lang.reflect.Array;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Curso
 */
public class matriz extends javax.swing.JFrame {

    /**
     * Creates new form matriz
     */
    ArrayList<JLabel> componenteslbl = new ArrayList<>();
    ArrayList<JTextField> componentestxt1 = new ArrayList<>();
    
    
    public matriz(String seleccion) {
        initComponents();
        agregarComponentes();
        crearvista(seleccion);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1_2 = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        txt1_1 = new javax.swing.JTextField();
        txt6_2 = new javax.swing.JTextField();
        lbl6 = new javax.swing.JLabel();
        txt6_1 = new javax.swing.JTextField();
        lbl11 = new javax.swing.JLabel();
        txt11_2 = new javax.swing.JTextField();
        txt11_1 = new javax.swing.JTextField();
        txt2_2 = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        txt2_1 = new javax.swing.JTextField();
        txt7_2 = new javax.swing.JTextField();
        lbl7 = new javax.swing.JLabel();
        txt7_1 = new javax.swing.JTextField();
        lbl12 = new javax.swing.JLabel();
        txt12_2 = new javax.swing.JTextField();
        txt12_1 = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        txt8_1 = new javax.swing.JTextField();
        lbl13 = new javax.swing.JLabel();
        txt13_2 = new javax.swing.JTextField();
        txt8_2 = new javax.swing.JTextField();
        txt3_1 = new javax.swing.JTextField();
        txt13_1 = new javax.swing.JTextField();
        txt3_2 = new javax.swing.JTextField();
        lbl8 = new javax.swing.JLabel();
        txt14_2 = new javax.swing.JTextField();
        txt4_1 = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        txt4_2 = new javax.swing.JTextField();
        txt9_2 = new javax.swing.JTextField();
        lbl9 = new javax.swing.JLabel();
        txt14_1 = new javax.swing.JTextField();
        txt9_1 = new javax.swing.JTextField();
        lbl14 = new javax.swing.JLabel();
        txt15_1 = new javax.swing.JTextField();
        txt10_1 = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        txt5_2 = new javax.swing.JTextField();
        lbl10 = new javax.swing.JLabel();
        txt10_2 = new javax.swing.JTextField();
        txt5_1 = new javax.swing.JTextField();
        txt15_2 = new javax.swing.JTextField();
        lbl_Titulo = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl23 = new javax.swing.JLabel();
        txt23_2 = new javax.swing.JTextField();
        txt25_2 = new javax.swing.JTextField();
        txt23_1 = new javax.swing.JTextField();
        txt24_2 = new javax.swing.JTextField();
        lbl21 = new javax.swing.JLabel();
        txt21_2 = new javax.swing.JTextField();
        txt21_1 = new javax.swing.JTextField();
        txt24_1 = new javax.swing.JTextField();
        lbl24 = new javax.swing.JLabel();
        txt25_1 = new javax.swing.JTextField();
        lbl22 = new javax.swing.JLabel();
        txt22_2 = new javax.swing.JTextField();
        txt22_1 = new javax.swing.JTextField();
        lbl25 = new javax.swing.JLabel();
        txt20_2 = new javax.swing.JTextField();
        lbl16 = new javax.swing.JLabel();
        txt16_2 = new javax.swing.JTextField();
        txt16_1 = new javax.swing.JTextField();
        lbl17 = new javax.swing.JLabel();
        txt17_2 = new javax.swing.JTextField();
        txt17_1 = new javax.swing.JTextField();
        lbl18 = new javax.swing.JLabel();
        txt18_2 = new javax.swing.JTextField();
        txt18_1 = new javax.swing.JTextField();
        txt19_2 = new javax.swing.JTextField();
        txt19_1 = new javax.swing.JTextField();
        lbl19 = new javax.swing.JLabel();
        txt20_1 = new javax.swing.JTextField();
        lbl20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1_2.setPreferredSize(new java.awt.Dimension(70, 20));

        lbl1.setText("--------------------");
        lbl1.setMaximumSize(new java.awt.Dimension(70, 14));
        lbl1.setMinimumSize(new java.awt.Dimension(70, 14));

        txt1_1.setPreferredSize(new java.awt.Dimension(6, 20));
        txt1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1_1ActionPerformed(evt);
            }
        });

        lbl6.setText("--------------------");

        lbl11.setText("--------------------");

        txt2_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt2_2.setName(""); // NOI18N

        lbl2.setText("--------------------");
        lbl2.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl2.setName(""); // NOI18N

        txt2_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt2_1.setName(""); // NOI18N
        txt2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2_1ActionPerformed(evt);
            }
        });

        txt7_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt7_2.setName(""); // NOI18N

        lbl7.setText("--------------------");
        lbl7.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl7.setName(""); // NOI18N

        txt7_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt7_1.setName(""); // NOI18N

        lbl12.setText("--------------------");
        lbl12.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl12.setName(""); // NOI18N

        txt12_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt12_2.setName(""); // NOI18N
        txt12_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt12_2ActionPerformed(evt);
            }
        });

        txt12_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt12_1.setName(""); // NOI18N

        lbl3.setText("--------------------");
        lbl3.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl3.setName(""); // NOI18N

        txt8_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt8_1.setName(""); // NOI18N

        lbl13.setText("--------------------");
        lbl13.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl13.setName(""); // NOI18N

        txt13_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt13_2.setName(""); // NOI18N

        txt8_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt8_2.setName(""); // NOI18N

        txt3_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt3_1.setName(""); // NOI18N

        txt13_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt13_1.setName(""); // NOI18N

        txt3_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt3_2.setName(""); // NOI18N

        lbl8.setText("--------------------");
        lbl8.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl8.setName(""); // NOI18N

        txt14_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt14_2.setName(""); // NOI18N

        txt4_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt4_1.setName(""); // NOI18N

        lbl4.setText("--------------------");
        lbl4.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl4.setName(""); // NOI18N

        txt4_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt4_2.setName(""); // NOI18N

        txt9_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt9_2.setName(""); // NOI18N

        lbl9.setText("--------------------");
        lbl9.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl9.setName(""); // NOI18N

        txt14_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt14_1.setName(""); // NOI18N

        txt9_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt9_1.setName(""); // NOI18N

        lbl14.setText("--------------------");
        lbl14.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl14.setName(""); // NOI18N

        txt15_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt15_1.setName(""); // NOI18N

        txt10_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt10_1.setName(""); // NOI18N

        lbl5.setText("--------------------");
        lbl5.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl5.setName(""); // NOI18N

        lbl15.setText("--------------------");
        lbl15.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl15.setName(""); // NOI18N

        txt5_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt5_2.setName(""); // NOI18N

        lbl10.setText("--------------------");
        lbl10.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl10.setName(""); // NOI18N

        txt10_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt10_2.setName(""); // NOI18N

        txt5_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt5_1.setName(""); // NOI18N

        txt15_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt15_2.setName(""); // NOI18N

        lbl_Titulo.setText("Ingrese unicamente numeros en la matriz");

        btn_aceptar.setText("Aceptar");

        btn_cancelar.setText("Cancelar");

        lbl23.setText("--------------------");
        lbl23.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl23.setName(""); // NOI18N

        txt23_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt23_2.setName(""); // NOI18N
        txt23_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt23_2ActionPerformed(evt);
            }
        });

        txt25_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt25_2.setName(""); // NOI18N

        txt23_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt23_1.setName(""); // NOI18N

        txt24_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt24_2.setName(""); // NOI18N

        lbl21.setText("--------------------");

        txt24_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt24_1.setName(""); // NOI18N

        lbl24.setText("--------------------");
        lbl24.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl24.setName(""); // NOI18N

        txt25_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt25_1.setName(""); // NOI18N

        lbl22.setText("--------------------");
        lbl22.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl22.setName(""); // NOI18N

        txt22_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt22_2.setName(""); // NOI18N
        txt22_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt22_2ActionPerformed(evt);
            }
        });

        txt22_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt22_1.setName(""); // NOI18N

        lbl25.setText("--------------------");
        lbl25.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl25.setName(""); // NOI18N

        txt20_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt20_2.setName(""); // NOI18N

        lbl16.setText("--------------------");

        lbl17.setText("--------------------");
        lbl17.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl17.setName(""); // NOI18N

        txt17_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt17_2.setName(""); // NOI18N
        txt17_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt17_2ActionPerformed(evt);
            }
        });

        txt17_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt17_1.setName(""); // NOI18N

        lbl18.setText("--------------------");
        lbl18.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl18.setName(""); // NOI18N

        txt18_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt18_2.setName(""); // NOI18N

        txt18_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt18_1.setName(""); // NOI18N

        txt19_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt19_2.setName(""); // NOI18N

        txt19_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt19_1.setName(""); // NOI18N

        lbl19.setText("--------------------");
        lbl19.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl19.setName(""); // NOI18N

        txt20_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt20_1.setName(""); // NOI18N

        lbl20.setText("--------------------");
        lbl20.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl20.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt16_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt16_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt17_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt17_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt18_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt18_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt19_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt19_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt20_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt20_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt21_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt21_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt22_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt22_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt23_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt23_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt24_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt24_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt25_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt25_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt11_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt11_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt12_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt12_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt13_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt13_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt14_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt14_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt9_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt15_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt15_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt10_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt10_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Titulo)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt9_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt10_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt10_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt15_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt15_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt14_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt14_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt13_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt13_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt12_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt12_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt11_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt11_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt20_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt20_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt19_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt19_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt18_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt18_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt17_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt17_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt16_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt16_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt25_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt25_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt24_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl24, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt24_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt23_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt23_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt22_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt22_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt21_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt21_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        lbl1.getAccessibleContext().setAccessibleName("--------------------------");
        lbl2.getAccessibleContext().setAccessibleName("--------------------------");
        lbl3.getAccessibleContext().setAccessibleName("--------------------------");
        lbl4.getAccessibleContext().setAccessibleName("--------------------------");
        lbl5.getAccessibleContext().setAccessibleName("--------------------------");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1_1ActionPerformed

    private void txt2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2_1ActionPerformed

    private void txt12_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt12_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt12_2ActionPerformed

    private void txt22_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt22_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt22_2ActionPerformed

    private void txt17_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt17_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt17_2ActionPerformed

    private void txt23_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt23_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt23_2ActionPerformed
    private void crearvista(String seleccion){
       
        switch(seleccion){
            
            case "0+0":
                String[] comp = {"lbl1","lbl2","txt1_1","txt1_2"}; 
                mostrar(comp);
                
                break;
            case "0+1":
                break;
            case "0+2":
                break;
            case "0+3":
                break;
            case "0+4":
                break;
            case "1+0":
                break;
            case "1+1":
                break;
            case "1+2":
                break;
            case "1+3":
                break;
            case "1+4":
                break;
            case "2+0":
                break;
            case "2+1":
                break;
            case "2+2":
                break;
            case "2+3":
                break;
            case "2+4":
                break;
            case "3+0":
                break;
            case "3+1":
                break;
            case "3+2":
                break;
            case "3+3":
                break;
            case "3+4":
                break;
            case "4+0":
                break;
            case "4+1":
                break;
            case "4+2":
                break;
            case "4+3":
                break;
            case "4+4":
                break;
            
                
        }
    }
    private void mostrar(String[] elementos){
        System.out.println(elementos[2]);
        for (int i = 0; i < elementos.length; i++) {
            
            for (int j = 0; j <componenteslbl.size(); j++) {
                
                if (componenteslbl.get(i).getName()==elementos[i]){
                    
                    componenteslbl.get(i).setVisible(true);
                    componenteslbl.get(i).setEnabled(true6);
                    
                }
                
            }
            for (int j = 0; j < 26; j++) {
               
                    if (componentestxt1.get(i).getName()== elementos[i]){
                    componentestxt1.get(i).setVisible(true);
                    componenteslbl.get(i+25).setVisible(true);
                    this.repaint();
                }
                
                
            }
        }
        
        
    }
    private void agregarComponentes(){
        componenteslbl.add(lbl1);
        componenteslbl.add(lbl2);
        componenteslbl.add(lbl3);
        componenteslbl.add(lbl4);
        componenteslbl.add(lbl5);
        componenteslbl.add(lbl6);
        componenteslbl.add(lbl7);
        componenteslbl.add(lbl8);
        componenteslbl.add(lbl9);
        componenteslbl.add(lbl10);
        componenteslbl.add(lbl11);
        componenteslbl.add(lbl12);
        componenteslbl.add(lbl13);
        componenteslbl.add(lbl14);
        componenteslbl.add(lbl15);
        componenteslbl.add(lbl16);
        componenteslbl.add(lbl17);
        componenteslbl.add(lbl18);
        componenteslbl.add(lbl19);
        componenteslbl.add(lbl20);
        componenteslbl.add(lbl21);
        componenteslbl.add(lbl22);
        componenteslbl.add(lbl23);
        componenteslbl.add(lbl24);
        componenteslbl.add(lbl25);
        
        componentestxt1.add(txt1_1);
        componentestxt1.add(txt2_1);
        componentestxt1.add(txt3_1);
        componentestxt1.add(txt4_1);
        componentestxt1.add(txt5_1);
        componentestxt1.add(txt6_1);
        componentestxt1.add(txt7_1);
        componentestxt1.add(txt8_1);
        componentestxt1.add(txt9_1);
        componentestxt1.add(txt10_1);
        componentestxt1.add(txt11_1);
        componentestxt1.add(txt12_1);
        componentestxt1.add(txt13_1);
        componentestxt1.add(txt14_1);
        componentestxt1.add(txt15_1);
        componentestxt1.add(txt16_1);
        componentestxt1.add(txt17_1);
        componentestxt1.add(txt18_1);
        componentestxt1.add(txt19_1);
        componentestxt1.add(txt20_1);
        componentestxt1.add(txt21_1);
        componentestxt1.add(txt22_1);
        componentestxt1.add(txt23_1);
        componentestxt1.add(txt24_1);
        componentestxt1.add(txt25_1);
        
        componentestxt1.add(txt1_2);
        componentestxt1.add(txt2_2);
        componentestxt1.add(txt3_2);
        componentestxt1.add(txt4_2);
        componentestxt1.add(txt5_2);
        componentestxt1.add(txt6_2);
        componentestxt1.add(txt7_2);
        componentestxt1.add(txt8_2);
        componentestxt1.add(txt9_2);
        componentestxt1.add(txt10_2);
        componentestxt1.add(txt11_2);
        componentestxt1.add(txt12_2);
        componentestxt1.add(txt13_2);
        componentestxt1.add(txt14_2);
        componentestxt1.add(txt15_2);
        componentestxt1.add(txt16_2);
        componentestxt1.add(txt17_2);
        componentestxt1.add(txt18_2);
        componentestxt1.add(txt19_2);
        componentestxt1.add(txt20_2);
        componentestxt1.add(txt21_2);
        componentestxt1.add(txt22_2);
        componentestxt1.add(txt23_2);
        componentestxt1.add(txt24_2);
        componentestxt1.add(txt25_2);
         for (int i = 0; i < componenteslbl.size(); i++) {
            componenteslbl.get(i).setVisible(false);
            
        }
         for (int i = 0; i < componentestxt1.size(); i++) {
            
            componentestxt1.get(i).setVisible(false);
        }
             
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                matriz m = new matriz("1+3");
                m.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JTextField txt10_1;
    private javax.swing.JTextField txt10_2;
    private javax.swing.JTextField txt11_1;
    private javax.swing.JTextField txt11_2;
    private javax.swing.JTextField txt12_1;
    private javax.swing.JTextField txt12_2;
    private javax.swing.JTextField txt13_1;
    private javax.swing.JTextField txt13_2;
    private javax.swing.JTextField txt14_1;
    private javax.swing.JTextField txt14_2;
    private javax.swing.JTextField txt15_1;
    private javax.swing.JTextField txt15_2;
    private javax.swing.JTextField txt16_1;
    private javax.swing.JTextField txt16_2;
    private javax.swing.JTextField txt17_1;
    private javax.swing.JTextField txt17_2;
    private javax.swing.JTextField txt18_1;
    private javax.swing.JTextField txt18_2;
    private javax.swing.JTextField txt19_1;
    private javax.swing.JTextField txt19_2;
    private javax.swing.JTextField txt1_1;
    private javax.swing.JTextField txt1_2;
    private javax.swing.JTextField txt20_1;
    private javax.swing.JTextField txt20_2;
    private javax.swing.JTextField txt21_1;
    private javax.swing.JTextField txt21_2;
    private javax.swing.JTextField txt22_1;
    private javax.swing.JTextField txt22_2;
    private javax.swing.JTextField txt23_1;
    private javax.swing.JTextField txt23_2;
    private javax.swing.JTextField txt24_1;
    private javax.swing.JTextField txt24_2;
    private javax.swing.JTextField txt25_1;
    private javax.swing.JTextField txt25_2;
    private javax.swing.JTextField txt2_1;
    private javax.swing.JTextField txt2_2;
    private javax.swing.JTextField txt3_1;
    private javax.swing.JTextField txt3_2;
    private javax.swing.JTextField txt4_1;
    private javax.swing.JTextField txt4_2;
    private javax.swing.JTextField txt5_1;
    private javax.swing.JTextField txt5_2;
    private javax.swing.JTextField txt6_1;
    private javax.swing.JTextField txt6_2;
    private javax.swing.JTextField txt7_1;
    private javax.swing.JTextField txt7_2;
    private javax.swing.JTextField txt8_1;
    private javax.swing.JTextField txt8_2;
    private javax.swing.JTextField txt9_1;
    private javax.swing.JTextField txt9_2;
    // End of variables declaration//GEN-END:variables
}
