/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Datos.Matriz;
import com.sun.javafx.scene.layout.region.Margins;
import java.awt.Component;
import java.awt.Font;
import java.lang.reflect.Array;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.lang.reflect.Field;
import java.math.BigDecimal;
import org.apfloat.Apfloat;
/**
 *
 * @author Curso
 */
public class ventanaMatriz extends javax.swing.JFrame {

    /**
     * Creates new form matriz
     */
    Principal principal ;
    private Apfloat convertidor1;
    private Apfloat convertidor2;
    private ArrayList<JLabel> componenteslbl = new ArrayList<>();
    private ArrayList<JTextField> componentestxt1 = new ArrayList<>();
    private ArrayList<JTextField> componentestxt2 = new ArrayList<>();
    private String seleccion ;
    public ventanaMatriz(String seleccion,Principal p ) {
        initComponents();
        agregarComponentes();
        crearvista(seleccion);
        this.seleccion = seleccion;
        this.principal = p;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jSeparator1 = new javax.swing.JSeparator();
        txt1_2 = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        txt1_1 = new javax.swing.JTextField();
        txt6_2 = new javax.swing.JTextField();
        lbl6 = new javax.swing.JLabel();
        txt6_1 = new javax.swing.JTextField();
        lbl11 = new javax.swing.JLabel();
        txt11_2 = new javax.swing.JTextField();
        txt11_1 = new javax.swing.JTextField();
        txt2_2 = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        txt2_1 = new javax.swing.JTextField();
        txt7_2 = new javax.swing.JTextField();
        lbl7 = new javax.swing.JLabel();
        txt7_1 = new javax.swing.JTextField();
        lbl12 = new javax.swing.JLabel();
        txt12_2 = new javax.swing.JTextField();
        txt12_1 = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        txt8_1 = new javax.swing.JTextField();
        lbl13 = new javax.swing.JLabel();
        txt13_2 = new javax.swing.JTextField();
        txt8_2 = new javax.swing.JTextField();
        txt3_1 = new javax.swing.JTextField();
        txt13_1 = new javax.swing.JTextField();
        txt3_2 = new javax.swing.JTextField();
        lbl8 = new javax.swing.JLabel();
        txt14_2 = new javax.swing.JTextField();
        txt4_1 = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        txt4_2 = new javax.swing.JTextField();
        txt9_2 = new javax.swing.JTextField();
        lbl9 = new javax.swing.JLabel();
        txt14_1 = new javax.swing.JTextField();
        txt9_1 = new javax.swing.JTextField();
        lbl14 = new javax.swing.JLabel();
        txt15_1 = new javax.swing.JTextField();
        txt10_1 = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        txt5_2 = new javax.swing.JTextField();
        lbl10 = new javax.swing.JLabel();
        txt10_2 = new javax.swing.JTextField();
        txt5_1 = new javax.swing.JTextField();
        txt15_2 = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl23 = new javax.swing.JLabel();
        txt23_2 = new javax.swing.JTextField();
        txt25_2 = new javax.swing.JTextField();
        txt23_1 = new javax.swing.JTextField();
        txt24_2 = new javax.swing.JTextField();
        lbl21 = new javax.swing.JLabel();
        txt21_2 = new javax.swing.JTextField();
        txt21_1 = new javax.swing.JTextField();
        txt24_1 = new javax.swing.JTextField();
        lbl24 = new javax.swing.JLabel();
        txt25_1 = new javax.swing.JTextField();
        lbl22 = new javax.swing.JLabel();
        txt22_2 = new javax.swing.JTextField();
        txt22_1 = new javax.swing.JTextField();
        lbl25 = new javax.swing.JLabel();
        txt20_2 = new javax.swing.JTextField();
        lbl16 = new javax.swing.JLabel();
        txt16_2 = new javax.swing.JTextField();
        txt16_1 = new javax.swing.JTextField();
        lbl17 = new javax.swing.JLabel();
        txt17_2 = new javax.swing.JTextField();
        txt17_1 = new javax.swing.JTextField();
        lbl18 = new javax.swing.JLabel();
        txt18_2 = new javax.swing.JTextField();
        txt18_1 = new javax.swing.JTextField();
        txt19_2 = new javax.swing.JTextField();
        txt19_1 = new javax.swing.JTextField();
        lbl19 = new javax.swing.JLabel();
        txt20_1 = new javax.swing.JTextField();
        lbl20 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 200));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 200));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 200));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 200));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 500), new java.awt.Dimension(0, 500), new java.awt.Dimension(32767, 500));
        jLabel1 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 400), new java.awt.Dimension(0, 400), new java.awt.Dimension(32767, 400));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txt1_2.setText("1");
        txt1_2.setPreferredSize(new java.awt.Dimension(70, 20));
        txt1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1_2ActionPerformed(evt);
            }
        });

        lbl1.setText("--------------------");
        lbl1.setAlignmentX(0.5F);
        lbl1.setMaximumSize(new java.awt.Dimension(70, 14));
        lbl1.setMinimumSize(new java.awt.Dimension(70, 14));

        txt1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1_1ActionPerformed(evt);
            }
        });

        txt6_2.setText("1");

        lbl6.setText("--------------------");
        lbl6.setAlignmentX(0.5F);

        lbl11.setText("--------------------");
        lbl11.setAlignmentX(0.5F);

        txt11_2.setText("1");

        txt2_2.setText("1");
        txt2_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt2_2.setName(""); // NOI18N

        lbl2.setText("--------------------");
        lbl2.setAlignmentX(0.5F);
        lbl2.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl2.setName(""); // NOI18N

        txt2_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt2_1.setName(""); // NOI18N
        txt2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2_1ActionPerformed(evt);
            }
        });

        txt7_2.setText("1");
        txt7_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt7_2.setName(""); // NOI18N

        lbl7.setText("--------------------");
        lbl7.setAlignmentX(0.5F);
        lbl7.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl7.setName(""); // NOI18N

        txt7_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt7_1.setName(""); // NOI18N

        lbl12.setText("--------------------");
        lbl12.setAlignmentX(0.5F);
        lbl12.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl12.setName(""); // NOI18N

        txt12_2.setText("1");
        txt12_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt12_2.setName(""); // NOI18N
        txt12_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt12_2ActionPerformed(evt);
            }
        });

        txt12_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt12_1.setName(""); // NOI18N

        lbl3.setText("--------------------");
        lbl3.setAlignmentX(0.5F);
        lbl3.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl3.setName(""); // NOI18N

        txt8_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt8_1.setName(""); // NOI18N

        lbl13.setText("--------------------");
        lbl13.setAlignmentX(0.5F);
        lbl13.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl13.setName(""); // NOI18N

        txt13_2.setText("1");
        txt13_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt13_2.setName(""); // NOI18N

        txt8_2.setText("1");
        txt8_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt8_2.setName(""); // NOI18N

        txt3_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt3_1.setName(""); // NOI18N

        txt13_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt13_1.setName(""); // NOI18N

        txt3_2.setText("1");
        txt3_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt3_2.setName(""); // NOI18N

        lbl8.setText("--------------------");
        lbl8.setAlignmentX(0.5F);
        lbl8.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl8.setName(""); // NOI18N

        txt14_2.setText("1");
        txt14_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt14_2.setName(""); // NOI18N

        txt4_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt4_1.setName(""); // NOI18N

        lbl4.setText("--------------------");
        lbl4.setAlignmentX(0.5F);
        lbl4.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl4.setName(""); // NOI18N

        txt4_2.setText("1");
        txt4_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt4_2.setName(""); // NOI18N

        txt9_2.setText("1");
        txt9_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt9_2.setName(""); // NOI18N

        lbl9.setText("--------------------");
        lbl9.setAlignmentX(0.5F);
        lbl9.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl9.setName(""); // NOI18N

        txt14_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt14_1.setName(""); // NOI18N

        txt9_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt9_1.setName(""); // NOI18N

        lbl14.setText("--------------------");
        lbl14.setAlignmentX(0.5F);
        lbl14.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl14.setName(""); // NOI18N

        txt15_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt15_1.setName(""); // NOI18N

        txt10_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt10_1.setName(""); // NOI18N

        lbl5.setText("--------------------");
        lbl5.setAlignmentX(0.5F);
        lbl5.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl5.setName(""); // NOI18N

        lbl15.setText("--------------------");
        lbl15.setAlignmentX(0.5F);
        lbl15.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl15.setName(""); // NOI18N

        txt5_2.setText("1");
        txt5_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt5_2.setName(""); // NOI18N
        txt5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5_2ActionPerformed(evt);
            }
        });

        lbl10.setText("--------------------");
        lbl10.setAlignmentX(0.5F);
        lbl10.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl10.setName(""); // NOI18N

        txt10_2.setText("1");
        txt10_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt10_2.setName(""); // NOI18N

        txt5_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt5_1.setName(""); // NOI18N

        txt15_2.setText("1");
        txt15_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt15_2.setName(""); // NOI18N
        txt15_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt15_2ActionPerformed(evt);
            }
        });

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        lbl23.setText("--------------------");
        lbl23.setAlignmentX(0.5F);
        lbl23.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl23.setName(""); // NOI18N

        txt23_2.setText("1");
        txt23_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt23_2.setName(""); // NOI18N
        txt23_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt23_2ActionPerformed(evt);
            }
        });

        txt25_2.setText("1");
        txt25_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt25_2.setName(""); // NOI18N

        txt23_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt23_1.setName(""); // NOI18N

        txt24_2.setText("1");
        txt24_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt24_2.setName(""); // NOI18N

        lbl21.setText("--------------------");
        lbl21.setAlignmentX(0.5F);

        txt21_2.setText("1");

        txt24_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt24_1.setName(""); // NOI18N

        lbl24.setText("--------------------");
        lbl24.setAlignmentX(0.5F);
        lbl24.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl24.setName(""); // NOI18N

        txt25_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt25_1.setName(""); // NOI18N

        lbl22.setText("--------------------");
        lbl22.setAlignmentX(0.5F);
        lbl22.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl22.setName(""); // NOI18N

        txt22_2.setText("1");
        txt22_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt22_2.setName(""); // NOI18N
        txt22_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt22_2ActionPerformed(evt);
            }
        });

        txt22_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt22_1.setName(""); // NOI18N

        lbl25.setText("--------------------");
        lbl25.setAlignmentX(0.5F);
        lbl25.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl25.setName(""); // NOI18N

        txt20_2.setText("1");
        txt20_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt20_2.setName(""); // NOI18N

        lbl16.setText("--------------------");
        lbl16.setAlignmentX(0.5F);

        txt16_2.setText("1");

        lbl17.setText("--------------------");
        lbl17.setAlignmentX(0.5F);
        lbl17.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl17.setName(""); // NOI18N

        txt17_2.setText("1");
        txt17_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt17_2.setName(""); // NOI18N
        txt17_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt17_2ActionPerformed(evt);
            }
        });

        txt17_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt17_1.setName(""); // NOI18N

        lbl18.setText("--------------------");
        lbl18.setAlignmentX(0.5F);
        lbl18.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl18.setName(""); // NOI18N

        txt18_2.setText("1");
        txt18_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt18_2.setName(""); // NOI18N

        txt18_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt18_1.setName(""); // NOI18N

        txt19_2.setText("1");
        txt19_2.setMinimumSize(new java.awt.Dimension(70, 0));
        txt19_2.setName(""); // NOI18N
        txt19_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt19_2ActionPerformed(evt);
            }
        });

        txt19_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt19_1.setName(""); // NOI18N

        lbl19.setText("--------------------");
        lbl19.setAlignmentX(0.5F);
        lbl19.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl19.setName(""); // NOI18N

        txt20_1.setMinimumSize(new java.awt.Dimension(70, 0));
        txt20_1.setName(""); // NOI18N

        lbl20.setText("--------------------");
        lbl20.setAlignmentX(0.5F);
        lbl20.setMinimumSize(new java.awt.Dimension(70, 0));
        lbl20.setName(""); // NOI18N

        jLabel1.setText("Ingrese valores a la matriz en caso de querer que sean enteros no modiicar el denominador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt16_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt16_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt11_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt11_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt21_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt21_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt22_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt22_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt17_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt17_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt12_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt12_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt23_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt23_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt18_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt18_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt13_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt13_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt24_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt24_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt19_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt19_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt14_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt14_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt9_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt25_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt25_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt20_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt20_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt15_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt15_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt10_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt10_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(510, 510, 510)
                        .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt13_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt13_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt18_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt18_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(txt23_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt23_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txt2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt12_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt12_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt17_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt17_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(txt22_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt22_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt10_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt10_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt15_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt15_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt20_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt20_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(txt25_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt25_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txt4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt9_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt14_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt14_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(txt19_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt19_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(txt24_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(lbl24, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(txt24_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(filler6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(txt1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(txt6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(txt6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(txt11_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(txt11_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(txt16_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(txt16_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45)
                                    .addComponent(txt21_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(lbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(txt21_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        txt1_2.getAccessibleContext().setAccessibleName(txt11_2.getUIClassID());
        lbl1.getAccessibleContext().setAccessibleName("lbl1");
        txt1_1.getAccessibleContext().setAccessibleName("txt1_1");
        lbl6.getAccessibleContext().setAccessibleName(lbl1.getUIClassID());
        lbl11.getAccessibleContext().setAccessibleName("");
        txt2_2.getAccessibleContext().setAccessibleName("txt2_2");
        lbl2.getAccessibleContext().setAccessibleName("lbl2");
        lbl7.getAccessibleContext().setAccessibleName(getName());
        lbl12.getAccessibleContext().setAccessibleName("");
        lbl3.getAccessibleContext().setAccessibleName("lbl3");
        lbl13.getAccessibleContext().setAccessibleName("");
        txt3_1.getAccessibleContext().setAccessibleName("txt3_1");
        txt3_2.getAccessibleContext().setAccessibleName("txt3_2");
        lbl8.getAccessibleContext().setAccessibleName(getName());
        txt4_1.getAccessibleContext().setAccessibleName("txt4_1");
        lbl4.getAccessibleContext().setAccessibleName(lbl4.getUIClassID());
        lbl9.getAccessibleContext().setAccessibleName(getName());
        lbl14.getAccessibleContext().setAccessibleName("");
        lbl5.getAccessibleContext().setAccessibleName(lbl5.getUIClassID());
        lbl15.getAccessibleContext().setAccessibleName("");
        lbl10.getAccessibleContext().setAccessibleName(getName());
        lbl23.getAccessibleContext().setAccessibleName("");
        lbl21.getAccessibleContext().setAccessibleName("");
        lbl24.getAccessibleContext().setAccessibleName("");
        lbl22.getAccessibleContext().setAccessibleName("");
        lbl25.getAccessibleContext().setAccessibleName("");
        lbl16.getAccessibleContext().setAccessibleName("");
        lbl17.getAccessibleContext().setAccessibleName("");
        lbl18.getAccessibleContext().setAccessibleName("");
        lbl19.getAccessibleContext().setAccessibleName("");
        lbl20.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1_1ActionPerformed

    private void txt2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2_1ActionPerformed

    private void txt12_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt12_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt12_2ActionPerformed

    private void txt22_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt22_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt22_2ActionPerformed

    private void txt17_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt17_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt17_2ActionPerformed

    private void txt23_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt23_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt23_2ActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txt1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1_2ActionPerformed

    private void txt5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5_2ActionPerformed

    private void txt15_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt15_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt15_2ActionPerformed

    private void txt19_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt19_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt19_2ActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
       /*convertidor1 = new Apfloat("4",20);
       convertidor2 = new Apfloat("3",20);
       convertidor1 = convertidor1.divide(convertidor2);
       Double b = convertidor1.doubleValue();*/
       
        switch(seleccion){
                
            case "0+0":
                String [] txt1 = {"0","-"};
                agregarMatriz(txt1);
                
                break;
            case "0+1":
                String [] txt2 = {"0","1","-"};
                agregarMatriz(txt2);
                
                break;
            case "0+2":
                String [] txt3 = {"0","1","2","-"};

                agregarMatriz(txt3);
                break;
            case "0+3":
                String [] txt4 = {"0","1","2","3","-"};
 
                agregarMatriz(txt4);
                break;
            case "0+4":
                String [] txt5 = {"0","1","2","3","4","-"}; 
                agregarMatriz(txt5);
                break;
            case "1+0":
                String [] txt6 = {"0","-","5","-"};
                agregarMatriz(txt6);
                break;
            case "1+1":
                String [] txt7 = {"0","1","-","5","6","-"}; 
                agregarMatriz(txt7);
                break;
            case "1+2":
                String [] txt8 = {"0","1","2","-","5","6","7","-"}; 
                agregarMatriz(txt8);
                break;
            case "1+3":
                String [] txt9 = {"0","1","2","3","-","5","6","7","8","-"};
                agregarMatriz(txt9);
                break;
            case "1+4":
                String [] txt10 = {"0","1","2","3","4","-","5","6","7","8","9","-"};
                agregarMatriz(txt10);
                break;
            case "2+0":
                String [] txt11 = {"0","-","5","-","10","-"};
                agregarMatriz(txt11);
                break;
            case "2+1":
                String [] txt12 = {"0","1","-","5","6","-","11","10","-"}; 
                agregarMatriz(txt12);
                break;
            case "2+2":
                String [] txt13 = {"0","1","2","-","5","6","7","-","10","11","12","-"};
                agregarMatriz(txt13);
                break;
            case "2+3":
                String [] txt14 = {"0","1","2","3","-","5","6","7","8","-","10","11","12","13","-"};
                agregarMatriz(txt14);
                break;
            case "2+4":
                String [] txt15 = {"0","1","2","3","4","-","5","6","7","8","9","-","10","11","12","13","14","-"};
                agregarMatriz(txt15);
                break;
            case "3+0":
                String [] txt16 = {"0","-","5","-","10","-","15","-"};
                agregarMatriz(txt16);
                break;
            case "3+1":
                String [] txt17 = {"0","1","-","5","6","-","10","11","-","15","16","-"};
                agregarMatriz(txt17);
                break;
            case "3+2":
                String [] txt18 = {"0","1","2","-","5","6","7","-","10","11","12","-","15","16","17","-"};
                agregarMatriz(txt18);
                break;
            case "3+3":
                String [] txt19 = {"0","1","2","3","-","5","6","7","8","-","10","11","12","13","-","15","16","17","18","-"};
                agregarMatriz(txt19);
                break;
            case "3+4":
                String [] txt20 = {"0","1","2","3","4","-","5","6","7","8","9","-","10","11","12","13","14","-","15","16","17","18","19","-"};
                agregarMatriz(txt20);
                break;
            case "4+0":
                String [] txt21 = {"0","-","5","-","10","-","15","-","20","-"};
                agregarMatriz(txt21);
                break;
            case "4+1":
                String [] txt22 = {"0","1","-","5","6","-","10","11","-","15","16","-","20","21","-"};
                agregarMatriz(txt22);
                break;
            case "4+2":
                String [] txt23 = {"0","1","2","-","5","6","7","-","10","11","12","-","15","16","17","-","20","21","22","-"};
                agregarMatriz(txt23);
                break;
            case "4+3":
                String [] txt24 = {"0","1","2","3","-","5","6","7","8","-","10","11","12","13","-","15","16","17","18","-","20","21","22","23","-"};
                agregarMatriz(txt24);
                break;
            case "4+4":
                String [] txt25 = {"0","1","2","3","4","-","5","6","7","8","9","-","10","11","12","13","14","-","15","16","17","18","19","-","20","21","22","23","24","-"};
                agregarMatriz(txt25);
                break;
            
                
        }
        
        
    }//GEN-LAST:event_btn_aceptarActionPerformed
    private boolean matrizCorrecta(String[] txt){
        for (int i = 0; i < txt.length; i++) {
            if (txt[i].equals("-")){  
                
            }
            else{
                 if (componentestxt1.get(Integer.parseInt(txt[i])).getText().matches("[0-9]+")&&
                         componentestxt2.get(Integer.parseInt(txt[i])).getText().matches("[0-9]+")
                         
                         ){
                 
                 }
                 else{
                     return false;
                 }
                                            
            }
            
            
        }
        return true;
    }
    private void crearvista(String seleccion){
        
        switch(seleccion){
                
            case "0+0":
                String [] txt1 = {"0"};
                mostrar(txt1);
                
                break;
            case "0+1":
                String [] txt2 = {"0","1"};
 
                mostrar(txt2);
                break;
            case "0+2":
                String [] txt3 = {"0","1","2"};

                mostrar(txt3);
                break;
            case "0+3":
                String [] txt4 = {"0","1","2","3"};
 
                mostrar(txt4);
                break;
            case "0+4":
                String [] txt5 = {"0","1","2","3","4"}; 
                mostrar(txt5);
                break;
            case "1+0":
                String [] txt6 = {"0","5"};
                mostrar(txt6);
                break;
            case "1+1":
                String [] txt7 = {"0","1","5","6"}; 
                mostrar(txt7);
                break;
            case "1+2":
                String [] txt8 = {"0","5","1","2","6","7"}; 
                mostrar(txt8);
                break;
            case "1+3":
                String [] txt9 = {"0","5","1","2","3","6","7","8"};
                mostrar(txt9);
                break;
            case "1+4":
                String [] txt10 = {"0","5","1","2","3","4","6","7","8","9"};
                mostrar(txt10);
                break;
            case "2+0":
                String [] txt11 = {"0","5","10"};
                mostrar(txt11);
                break;
            case "2+1":
                String [] txt12 = {"0","5","10","1","6","11"}; 
                mostrar(txt12);
                break;
            case "2+2":
                String [] txt13 = {"0","5","6","10","1","2","7","11","12"};
                mostrar(txt13);
                break;
            case "2+3":
                String [] txt14 = {"0","5","6","10","1","2","7","11","12","3","8","13"};
                mostrar(txt14);
                break;
            case "2+4":
                String [] txt15 = {"0","5","6","10","1","2","7","11","12","3","8","13","14","4","9"};
                mostrar(txt15);
                break;
            case "3+0":
                String [] txt16 = {"0","5","10","15"};
                mostrar(txt16);
                break;
            case "3+1":
                String [] txt17 = {"0","5","10","15","1","6","11","16"};
                mostrar(txt17);
                break;
            case "3+2":
                String [] txt18 = {"0","5","10","15","1","6","11","16","2","12","17","7"};
                mostrar(txt18);
                break;
            case "3+3":
                String [] txt19 = {"0","5","10","15","1","6","11","16","2","12","17","18","13","3","7","8"};
                mostrar(txt19);
                break;
            case "3+4":
                String [] txt20 = {"0","5","4","10","15","1","6","11","16","2","12","17","18","13","3","7","8","9","14","19"};
                mostrar(txt20);
                break;
            case "4+0":
                String [] txt21 = {"0","5","10","15","20"};
                mostrar(txt21);
                break;
            case "4+1":
                String [] txt22 = {"0","5","10","15","20","1","6","11","16","21"};
                mostrar(txt22);
                break;
            case "4+2":
                String [] txt23 = {"0","5","10","15","20","1","6","11","16","21","2","17","12","22","7"};
                mostrar(txt23);
                break;
            case "4+3":
                String [] txt24 = {"0","5","10","15","20","1","6","11","16","21","2","17","12","22","7","8","3","13","18","23"};
                mostrar(txt24);
                break;
            case "4+4":
                String [] txt25 = {"0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24"};
                mostrar(txt25);
                break;
            
                
        }
    }
    private void mostrar(String[] txt){     
        for (int i = 0; i < txt.length; i++) {         
            for (int j = 0; j <componenteslbl.size(); j++) { 
                
                if (componenteslbl.get(j).getName().equals(txt[i])){
                                    
                    componenteslbl.get(j).setVisible(true);    
                }
                
            }
        }
        for (int i = 0; i < txt.length; i++) {
            for (int j = 0; j < componentestxt1.size(); j++) {             
                    if (componentestxt1.get(j).getName().equals(txt[i])){
                    componentestxt1.get(j).setVisible(true);
                    componentestxt2.get(j).setVisible(true);
                        
                }  
            }
        }
        this.revalidate();
        this.repaint();
        
        
    }
    private void agregarMatriz(String[] txt){
        if (matrizCorrecta(txt)){
            ArrayList<Double> arraytmp = new ArrayList<Double>();
            for (int i = 0; i < txt.length; i++) {
                if (txt[i].equals("-")){  
                    principal.getMatrizPrincipal().añadirFila(new ArrayList<>(arraytmp));            
                    arraytmp.clear();
                }
                else{
                        double num1 = 0;
                        double num2 = 0;
                        double result = 0;
                        num1 = Double.parseDouble(componentestxt1.get(Integer.parseInt(txt[i])).getText());                      
                        num2 = Double.parseDouble(componentestxt2.get(Integer.parseInt(txt[i])).getText());
                        result = num1/num2;
                        arraytmp.add(result);                            
                }
            
            
            }
        }
        else{
            JOptionPane.showMessageDialog(null,
                    "La matriz que se ingreso se ecuentra incorrecta ,recuerde que no puede poseeer ceros,ni letras , ni encontrarse vacia");
        
        }
        
        
    }
    
    private void agregarComponentes(){
        componenteslbl.add(lbl1);
            
        componenteslbl.add(lbl2);
        componenteslbl.add(lbl3);
        componenteslbl.add(lbl4);
        componenteslbl.add(lbl5);
        componenteslbl.add(lbl6);
        componenteslbl.add(lbl7);
        componenteslbl.add(lbl8);
        componenteslbl.add(lbl9);
        componenteslbl.add(lbl10);
        componenteslbl.add(lbl11);
        componenteslbl.add(lbl12);
        componenteslbl.add(lbl13);
        componenteslbl.add(lbl14);
        componenteslbl.add(lbl15);
        componenteslbl.add(lbl16);
        componenteslbl.add(lbl17);
        componenteslbl.add(lbl18);
        componenteslbl.add(lbl19);
        componenteslbl.add(lbl20);
        componenteslbl.add(lbl21);
        componenteslbl.add(lbl22);
        componenteslbl.add(lbl23);
        componenteslbl.add(lbl24);
        componenteslbl.add(lbl25);
        
        componentestxt1.add(txt1_1);
        componentestxt1.add(txt2_1);
        componentestxt1.add(txt3_1);
        componentestxt1.add(txt4_1);
        componentestxt1.add(txt5_1);
        componentestxt1.add(txt6_1);
        componentestxt1.add(txt7_1);
        componentestxt1.add(txt8_1);
        componentestxt1.add(txt9_1);
        componentestxt1.add(txt10_1);
        componentestxt1.add(txt11_1);
        componentestxt1.add(txt12_1);
        componentestxt1.add(txt13_1);
        componentestxt1.add(txt14_1);
        componentestxt1.add(txt15_1);
        componentestxt1.add(txt16_1);
        componentestxt1.add(txt17_1);
        componentestxt1.add(txt18_1);
        componentestxt1.add(txt19_1);
        componentestxt1.add(txt20_1);
        componentestxt1.add(txt21_1);
        componentestxt1.add(txt22_1);
        componentestxt1.add(txt23_1);
        componentestxt1.add(txt24_1);
        componentestxt1.add(txt25_1);
        
        componentestxt2.add(txt1_2);
        componentestxt2.add(txt2_2);
        componentestxt2.add(txt3_2);
        componentestxt2.add(txt4_2);
        componentestxt2.add(txt5_2);
        componentestxt2.add(txt6_2);
        componentestxt2.add(txt7_2);
        componentestxt2.add(txt8_2);
        componentestxt2.add(txt9_2);
        componentestxt2.add(txt10_2);
        componentestxt2.add(txt11_2);
        componentestxt2.add(txt12_2);
        componentestxt2.add(txt13_2);
        componentestxt2.add(txt14_2);
        componentestxt2.add(txt15_2);
        componentestxt2.add(txt16_2);
        componentestxt2.add(txt17_2);
        componentestxt2.add(txt18_2);
        componentestxt2.add(txt19_2);
        componentestxt2.add(txt20_2);
        componentestxt2.add(txt21_2);
        componentestxt2.add(txt22_2);
        componentestxt2.add(txt23_2);
        componentestxt2.add(txt24_2);
        componentestxt2.add(txt25_2);
        Font font = componenteslbl.get(0).getFont();
        Font font1 = new Font(font.getName(),Font.PLAIN, font.getSize()+4);
         for (int i = 0; i < componenteslbl.size(); i++) {
            
            componenteslbl.get(i).setFont(font1);
            componenteslbl.get(i).setVisible(false);
            componenteslbl.get(i).setName(i+"");
            
        }
         for (int i = 0; i < componentestxt1.size(); i++) {
            
            componentestxt1.get(i).setVisible(false);
            componentestxt1.get(i).setName(i+"");
            componentestxt1.get(i).setHorizontalAlignment(JTextField.CENTER);
           componentestxt2.get(i).setVisible(false);
            componentestxt2.get(i).setName(i+"");
            componentestxt2.get(i).setHorizontalAlignment(JTextField.CENTER);
        }
             
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JTextField txt10_1;
    private javax.swing.JTextField txt10_2;
    private javax.swing.JTextField txt11_1;
    private javax.swing.JTextField txt11_2;
    private javax.swing.JTextField txt12_1;
    private javax.swing.JTextField txt12_2;
    private javax.swing.JTextField txt13_1;
    private javax.swing.JTextField txt13_2;
    private javax.swing.JTextField txt14_1;
    private javax.swing.JTextField txt14_2;
    private javax.swing.JTextField txt15_1;
    private javax.swing.JTextField txt15_2;
    private javax.swing.JTextField txt16_1;
    private javax.swing.JTextField txt16_2;
    private javax.swing.JTextField txt17_1;
    private javax.swing.JTextField txt17_2;
    private javax.swing.JTextField txt18_1;
    private javax.swing.JTextField txt18_2;
    private javax.swing.JTextField txt19_1;
    private javax.swing.JTextField txt19_2;
    private javax.swing.JTextField txt1_1;
    private javax.swing.JTextField txt1_2;
    private javax.swing.JTextField txt20_1;
    private javax.swing.JTextField txt20_2;
    private javax.swing.JTextField txt21_1;
    private javax.swing.JTextField txt21_2;
    private javax.swing.JTextField txt22_1;
    private javax.swing.JTextField txt22_2;
    private javax.swing.JTextField txt23_1;
    private javax.swing.JTextField txt23_2;
    private javax.swing.JTextField txt24_1;
    private javax.swing.JTextField txt24_2;
    private javax.swing.JTextField txt25_1;
    private javax.swing.JTextField txt25_2;
    private javax.swing.JTextField txt2_1;
    private javax.swing.JTextField txt2_2;
    private javax.swing.JTextField txt3_1;
    private javax.swing.JTextField txt3_2;
    private javax.swing.JTextField txt4_1;
    private javax.swing.JTextField txt4_2;
    private javax.swing.JTextField txt5_1;
    private javax.swing.JTextField txt5_2;
    private javax.swing.JTextField txt6_1;
    private javax.swing.JTextField txt6_2;
    private javax.swing.JTextField txt7_1;
    private javax.swing.JTextField txt7_2;
    private javax.swing.JTextField txt8_1;
    private javax.swing.JTextField txt8_2;
    private javax.swing.JTextField txt9_1;
    private javax.swing.JTextField txt9_2;
    // End of variables declaration//GEN-END:variables



}
